var canvas = document.getElementById("My_Olympic_canvas");
var ctx = canvas.getContext("2d");
var colour = "blue";
ctx.beginPath();
ctx.strokeStyle= colour;
ctx.lineWidth= 2;
ctx.arc(250,210,40,0,2*Math.PI);
ctx.stroke();
ctx.beginPath();
ctx.strokeStyle= "red";
ctx.lineWidth= 2;
ctx.arc(250,210,40,0,2*Math.PI);
ctx.stroke();
ctx.beginPath();
ctx.strokeStyle= "black";
ctx.lineWidth= 2;
ctx.arc(350,210,40,0,2*Math.PI);
ctx.stroke();
ctx.beginPath();
ctx.strokeStyle= "yellow";
ctx.lineWidth= 2;
ctx.arc(250,210,40,0,2*Math.PI);
ctx.stroke();
ctx.beginPath();
ctx.strokeStyle= "green";
ctx.lineWidth= 2;
ctx.arc(250,210,40,0,2*Math.PI);
ctx.stroke();


